### ISSUE TITLE
DragNDrop file import

### ISSUE THREAD

**Issue by gerep** [quiet-night-studio/dotmania#6]
System to drag a mp3 into the game tab to upload

Gerep found this Reddit post
https://www.reddit.com/r/godot/comments/j6mxpc/how_to_connect_the_files_dropped_scenetree_signal/

**Comment by ProjectEXT** [comment]
Added in [this commit](https://github.com/quiet-night-studio/dotmania/commit/05bdb0b0ac3279b0f2b1e7814cb73c843f52cb6e)
