### ISSUE TITLE
FadeIn sets volume to excessive amount

### ISSUE THREAD

**Issue by ProjectEXT** [quiet-night-studio/dotmania#9]
My guess, the fade_in function being called in _process is continuing as it updates without an eventual stop, setting the volume dB to the highest it can.

[Example Video](https://drive.google.com/file/d/1nzHj1hbwV0Scp_UJFVwbzC007AmwXIRV/view?usp=sharing)

**Comment by gerep** [comment]
That's weird behaviour.

If the `FadeIn` timer is not stopped (running), it calls the `fade_in` function which increments the decibels by 5, for 1 second.

I'll take a look at this but can you please experiment with it a little more?

Try changing the timer from 1 second to something less, also try updating the decibels incrementing from .5 to something less as well.

I would also add a `print` statement inside that `$FadeIn` block and make sure it stops printing after 1 second is passed.
